### ISSUE TITLE
Incorrect Input Type for ProcedureParserCustomValidatorEsque

### ISSUE THREAD

**Issue by sinclairzx81** [trpc/trpc#2453]
### Provide environment information

TypeScript 4.7.4

### Describe the bug

Hello, I'm currently trying to integrate TypeBox into tRPC, but am having some difficulties getting `input` type inferring correctly for `ProcedureParserCustomValidatorEsque` (note that `output` type is inferred correctly). When using the `inferProcedureInput` utility type, I can see that the input type is inferred correctly exterior to the router, but internally the `input` type always resolves to `unknown`.

The issue may be due to ProcedureParser not accounting for generic functions that return closures of ProcedureParserCustomValidatorEsque (which is a requirement for validators that require a compile step, such as TypeBox and Ajv). One possible solution may be to leverage TS 4.7 Instantiation Expressions.....

```typescript
function Boxed<T>() {
  return (): T => { throw 1 }
}

type T = ReturnType<typeof Boxed<{  // type T = () => {
  foo: string                       //   foo: string;
}>>                                 // }
```
But not sure how this would integrate around the existing rRpc inference logic.

### To reproduce

I've created a repro below that shows my current setup.

[TypeScript Playground Link](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKYGELmAGwygBo4A1AQ3wFcMBRKKaOAXzgDMmQ4ByAAQDOwAHYBjfBWBQA9DHQYARhAAe00bjAEiPAFChIsRCnmlkAZVEALDCAqsOXXoJHjJMuZiXLd+6PABUcBQCcDBQYKIOuE5hEdICRABu2jo60tJwALTZObl5+QWFRcWFaRkAEhRQwhgCAmVZJU3NLU2p7NRiMMAQwnB0ypiiMAA8yAB8ABSJVLQAXCgAlIgsqemNrZtbzQ0AksKcwWHUw9RQGA3bV9f5qRiDfnCudcaYWNaiANYMTFBw9zAMMIACYhH7MBA6OBwMDUBT4YCRIi-AQLSg0eiMaAAbQAulCnr0BMdhtBJsjoKi4LtAVAKPCMDSiBQYNARujaOCoONlpDodCBNRMFBJjx9jMEcC4BLaDxFgToTBLMABAA6ClQEIAXjg2NV+o1Anx0NWqx0HS6PT6ACEVBhgWN-spASCQuYrDYKFMBB7bAtkLyCephMSnh9PnAdWg3hotFBVTg8IRJj7rLZ5dDzjAzn1prMMAtOp9hBAAO7CZZa8aIBVwYDsOCTD1fBPhvMYxbLLM56X52tKpiluA1IfR7DhrlN8OqrkCdu0TsE01rDI3NfXPbCWEwBb7dSMDDDS7rk+tVIeDDUrfUGBjyOhcKiVUidhEAAKTFE9rOjOvowJF4QA2+zbtiPAAPrAhg7A8LiYEAI60FAwC1LBYEgTesE6OMqTBqGGHwDqsRPkwN5ECMCAsFMiyqohRCoKKBE8KQfJ1n+Cy2so9qTGOqoAPIKAAVoeMCTKx0IUP68iqmYYQiAA5pMizELWChSZgMlycIikZqwnYqZmtQQPgyRiWx256TW-L9IMIkjARY5TCI27LOsGoLM5N51iERYluWS4qSw8o6AMQyjA58hTEgkm8MxcBqbFlnrBAnwrhsp4ZUUDR8Te24LDgB5HusmUlaUOgXnAOUwNud5EY+z4HO+n7fucVXbiMAHyEBlW5TeYGQdBaE8HRyGoXBPBtZh+I4ToeHwJNhEPhEqqkbSFFUUptFIQxE29TAcWsRAe0cXawI8dJAnCcMYm1so6kYKqABy1AgAoRBKQZ-KoPdT0vW9Iq6UFykEucAjGaZSBBVZ-LdtURh3XAACMpDfXAABMrBLjoQWpKFdkLY5ZkI8jcCo4jSUZClqQ6EAA)

```typescript
import { TypeCompiler, ValueError } from '@sinclair/typebox/compiler'
import { Type, TSchema } from '@sinclair/typebox'
import * as trpc from '@trpc/server'

// ---------------------------------------------------------------
// Harness
// ---------------------------------------------------------------

function Expect<T>(value: T) {}

// ---------------------------------------------------------------
// Infrastructure
// ---------------------------------------------------------------

export class TypeCheckError extends Error {
  public errors: ValueError[]
  constructor(errors: IterableIterator<ValueError>) {
    super('Invalid value')
    this.errors = [...errors]
  }
}

function Boxed<T extends TSchema>(schema: T) {
  const check = TypeCompiler.Compile(schema)
  return (value: unknown) => {
    if (check.Check(value)) return value
    throw new TypeCheckError(check.Errors(value))
  }
}

// ---------------------------------------------------------------
// Input: Incorrect
// ---------------------------------------------------------------

type InputType = trpc.inferProcedureInput<
  typeof Input['_def']['queries']['Input']
>

const Input = trpc.router<{}>().query('Input', {
  input: Boxed(Type.Object({
    a: Type.String(),
    b: Type.String()
  })),
  resolve({ input }) {
    Expect<InputType>(input) // error: input is unknown
  },
})

Expect<InputType>({ a: '', b: '' }) // ok

// ---------------------------------------------------------------
// Output: Correct
// ---------------------------------------------------------------

type OutputType = trpc.inferProcedureOutput<
  typeof Output['_def']['queries']['Output']
>

const Output = trpc.router<{}>().query('Output', {
  output: Boxed(Type.Object({
    x: Type.Number(),
    y: Type.Number()
  })),
  resolve({ }) {
    return { x: 1, y: 2 }
  }
})

Expect<OutputType>({ x: 1, y: 1 }) // ok
```

### Additional information

It is possible to get inference working by replicating one of the hard coded `ProcedureParser` signatures. 

[TypeScript Playground Link](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKYGELmAGwygBo4A1AQ3wFcMBRKKaOAXzgDMmQ4ByAAQDOwAHYBjfBWBQA9DHQYARhAAe00bjAEiPAFChIsRCnmlkAZVEALDCAqsOXXoJHjJMuZiXLd+6PABUcBQCcDBQYKIOuE5hEdICRABu2jo60tJwALTZObl5+QWFRcWFaRkAEhRQwhgCAmVZJU3NLU2p7NRiMMAQwnB0ypiiMAA8yAB8ABSJVLQAXCgAlIgsqemNrZtbzQ0AksKcwWHUw9RQGA3bV9f5qRiDfnCudcaYWNaiANYMTFBw9zAMMIACYhH7MBA6OBwMDUBT4YCRIi-AQLSg0eiMaAAbQAulCnr0BMdhtBJsjoKi4LtAVAKPCMDSiBQYNARujaOCoONlpDodCBNRMFBJjx9jMEcC4BLaDxFgToTBLMABAA6ClQEIAXjg2NV+o1Anx0NWqx0HS6PT6ACEVBhgWN-spASCQuYrDYKFMBB7bAtkLyCephMSnh9PnAdWg3hotFBVTg8IRJj7rLZ5dDzjAzn0+fz1mAs0Cpay4AoMHBUEK4ArpVRgMCWRgzKgxAtprMMAtOp9hBAAO7CZZa8aIWvQ4DsOCTD1fBPhjsYxbLLM5usY8ehSxMftwGq76PYcNcmfh1VcgSL2jL2urE06M3rG7P657YSwmALfbqRgYYaXF9ANaVIPArfYP0PSNQnCURVREdgiAABSYUR7TORl32oUYCVAiAp3ArDsR4AB9YEMHYHhcSIgBHWgoGAWpKKIgiYEonRxlSYNQxYqDYlgpgsKIEYEBYKZFlVWiiFQUUWJ4Ug8xED8FltZR7UmQ9VQAeQUAArP8YEmPNoQof15FVMwwhEABzSZFmIWsFFMzBzMs4QbIzVhl3szNaggfBkkMuBFKwzyx35fpBn0kYWMPKZgpgZZ1ggT4FigAAlCJoMRT57SC4RS3g5FrK3ASrMsOAAE1q0K84xArMAWUsAkWHslh5R0AYhlGGL5CmJATN4OSywWHgeFCpLPh0IA)

```typescript
function Boxed<T extends TSchema>(schema: T) {
  const check = TypeCompiler.Compile(schema)
  return {
    // pretend to be yup
    validateSync: (value: unknown) => {
      if (check.Check(value)) return value
      throw new TypeCheckError(check.Errors(value))
    }
  }
}
```

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

**Comment by KATT** [comment]
Hmm, I'm unsure how to solve this & since I'm not using these validators myself I'll unlikely address it soon.

Likely, what needs to be done is to add a new type of parser which should be relatively straightforward.

- First, [look here](https://github.com/trpc/trpc/blob/ae2af0903ec622ecd3b0788a5faffe8af34e3b91/packages/server/src/internals/procedure.ts#L15-L43) for the parsers and add a new one
- Then, add a test for the validator: https://github.com/trpc/trpc/blob/main/packages/server/test/validators.test.ts
- Potentially, we also need to update [`getParseFn()`](https://github.com/trpc/trpc/blob/ae2af0903ec622ecd3b0788a5faffe8af34e3b91/packages/server/src/internals/procedure.ts#L71-L100)

**Comment by sinclairzx81** [comment]
@KATT Hi, thanks for quick reply! 

> Likely, what needs to be done is to add a new type of parser which should be relatively straightforward.

Yes, I've checked the code at the link provided, and I'm not sure it would be possible to add a TypeBox specific signature there.

The reason for this is due to TypeBox types not having an equivalent `z.parse()` or `yup.validateSync()` function. Because there is no equivalent function, it makes `getParseFn()` essentially impossible to implement. So I do think the `Boxed()` example above is probably the only way to go based on the current design of tRPC.

Just for some context though, TypeBox types do not include a validation function as the types it generates are intended to be passed directly into JSON schema compliant validators. Historically the library has deferred validation to libraries like Ajv (which is exceptionally [fast](https://moltar.github.io/typescript-runtime-type-benchmarks/)), but does have the trade off of requiring a compilation step in JavaScript (mostly for performance reasons)

I think adopting the `yup.validateSync()` work around is going to be the easiest option for now. But has tRPC considered implementing something similar to Fastify [Type Providers](https://www.fastify.io/docs/latest/Reference/Type-Providers) ? These providers allow implementers to create type system plugins that can provide both runtime validation and plugin type inference. 

Having something similar in tRPC would mean you could remove the hardcoded types and `getParseFn()` checks for each runtime type, and may also help speed up some of the inference logic in TypeScript.

**Comment by sachinraja** [comment]
Seems like a TS issue/unreliable inference because this works:
```ts
const inputValidator = Boxed(Type.Object({
  a: Type.String(),
  b: Type.String()
}))
  
const Input = trpc.router<{}>().query('Input', {
  input: inputValidator,
  resolve({ input }) {
    Expect<InputType>(input) // error: input is unknown
  },
})
```
[TypeScript Playground Link](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKYGELmAGwygBo4A1AQ3wFcMBRKKaOAXzgDMmQ4ByAAQDOwAHYBjfBWBQA9DHQYARhAAe00bjAEiPAFChIsRCnmlkAZVEALDCAqsOXXoJHjJMuZiXLd+6PABUcBQCcDBQYKIOuE5hEdICRABu2jo60tJwALTZObl5+QWFRcWFaRkAEhRQwhgCAmVZJU3NLU2p7NRiMMAQwnB0ypiiMAA8yAB8ABSJVLQAXCgAlIgsqemNrZtbzQ0AksKcwWHUw9RQGA3bV9f5qRiDfnCudcaYWNaiANYMTFBw9zAMMIACYhH7MBA6OBwMDUBT4YCRIi-AQLSg0eiMaAAbQAulCnr0BMdhtBJsjoKi4LtAVAKPCMDSiBQYNARujaOCoONlpDodCBNRMFBJjx9jMEcC4BLaDxFgToTBLMABAA6ClQEIAXjg2NV+o1Anx0NWqx0HS6PT6ACEVBhgWN-spASCQuYrDYKFMBB7bAtkLyCephMSnh9PnAdWg3hotFBVTg8IRJj7rLZ5dDzjAzn1prMMAtOp9hBAAO7CZZa8aIBVwYDsOCTD1fBPhvMYxbLLM56X52tKpiluA1IfR7DhrlN8OqrkCdu0TsE01rDI3NfXPbCWEwBb7dSMDDDS7rk+tVIeDDUrfUGBjyOhcKiVUidhEAAKTFE9rOjOvowJF4QA2+zbtiPAAPrAhg7A8LiYEAI60FAwC1LBYEgTesE6OMqTBqGIjbuiwDAiyzA6rayj2pMY6qgA8goABWh4wJMfL8hQ-ryKqZhhCIADmkyLMQtYKJxmDcbxwgCRmrCLnh8AYfAOqxE+TA3kQIwICwUyLKqiFEKgoqKTwpBsQRN4LOZMBESRrIkAS5wCBA+DJKxdZ-rJNb8v0gzMSMiljlMVnLOsGqWR5KpwEWJblkuwksPKOgDEMowBfIUxIBxvAmXAonZZ56wQJ8K4bKeZVFA0tE3tuCw4AeR7rOVTWlDoF5wFVMDbneymPs+Bzvp+37nB124jAB8hAe11U3mBkHQWhPD6chqFwTwI2YfiOE6PJU2dTe94qaqam0pp2mCXpSGGWt00wDlbEQDdCwUVRNH0UxwysbWyhiRgqoAHLUCAChEIJwneagP3-YDwMijJCVCQ5tTOa5SAJV5-LdtURjfXAACMpAQ3AABMrBLjoCWpMlfnrbe6VuTj+NwITuMFRkRWpDoQA)

**Comment by sinclairzx81** [comment]
@sachinraja Yeah, TS has some interesting rules around this. In theory though should be possible to infer for the `input` parameter, however the inference logic needs to account for the generic argument `T` in `Boxed<T extends TSchema>(...)` , and it's contribution to the returned closure.

I think inference via [Instantiation Expressions](https://github.com/babel/babel/issues/14322) is probably the correct way to approach this (as tRPC infers via `is` inference assertion), but would require a some new `Parser` type to hook onto. I'm not quite sure at this stage what that would look like in the current setup.

**Comment by sinclairzx81** [comment]
@sachinraja 

> Type providers are an interesting idea though. We could look into that for a potential performance win.

Hey, just as a follow up for Type Providers (and if they're an area of potential interest for the tRPC project), I've just spent a little bit of time putting together a quick draft to enable them over the existing the tRPC interface (as I currently understand it). These changes may help improve type inference performance, remove the hard code inference checks inside [procedure.ts](https://github.com/trpc/trpc/blob/ae2af0903ec622ecd3b0788a5faffe8af34e3b91/packages/server/src/internals/procedure.ts#L15-L43) and enable support for both dynamic and compiled validation routines.

I've included references for Zod, TypeBox and inline Json Schema for reference (for both router and client), but omitted any implementation details. You can view the draft at the link below.

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/PTAEFpK6dv4YpyXQFAlAFQEoAUBhUPAJwHsAXSgTwAcBTDYJ7ACwEsBnUL0AQ1C1yVCnXqgK+IqIY8AtrQA29OfQB2FPhXZk1EsqBIqyAN3Gs+JACYBjMlfpWeagGb0jam+L5qnJAK4a7KqgimQA5uw2LDas9DYA1tzsapzsDhJSAHRsvEKUNLL+nPTcAmly7IqWoKqxPlxy+qAAYnyc2i7U2GLE5Cbp7twA7nFGoCx8-gAeVZbdKW4eXqA2PqAARt6x9OxmThSs5P7hrKADAhyn7qAJKQ4HvUonKZxZTCxYHNz5Ir3+tCsWlKEjiEhItBsWWOFHcAAoAJS1eiHezNPg2Ly0CibShnRbudQrHxOEx8RTpLRkEg5L6MTAE5biPLtEqk9gCcLqdxRfgkcL+VQaAA0oPEZIpQKoJB4ZUElm05P4tCUUS0Oj0LkCNm0ulBWgmmGGZH8iicnABtGpOI2eNAVmoaj4lRsoDhAC97KLqADRRaGCQOgEdUiSasyAoqo43XwAFYmUWxzi6cCcHZyPiimT0W3TJEsAJBELZt4fTAANXJlOlAC4y2BQOHUjjK5KqTKALxutNxDM17BIjsAPjdEv89H7gQSajIwzUg5HU5nc-roAAotNnUoJ6vG02OoYTbDO+DIdCj+4ADwAbwAvqKAJKuQmeehDuGt6vUhFZACO45Iag4SyECfzkfxNF1NRgNA3dGzsZtVgpdQcS7CgIShGxkI0S9szIFxDwg9x3wAchArISIRVc0k8ap2BId1pgADgARlXVAOM4rjuI4tAWB4gTBKElBVwALXsdjhKk6ShL4zAuJYZ5IjUfjOL44IrRIHEACp+G4d1QBccgmhIz0rBIvj6GmTScQQg9xKsT8pQ1UAu0vLBQCs2FfH0rIHKwMQAEE1God8exUPh+ywBdR3JcdJzUadZ3nVyR3CjMsloSwSjhMd6CotArJs5xjxcDFxAcp8liJcQvPUKxuAChgqpfFZrzQRsj1oCD+0OLgAG0SJSbqKBIgBdTzpm8hrQHdPz7Ca+hgu6AB+WaskZXDvkG4aIPGkd+zUQUthINBbzksAFMwYo+C5VTeLQOycTMnALxPdCzxhK871FSrnyZd8HKc9VdCov8AKAki+CsczRXaxtdoofs5rIDZY3iCg4WvCY91AaZkayI65BOxFRQ6vdqAJomSfzRtbwRYVya6nr1up+EGfJoxk0UMx+yx5wRtAenUtAeG9ye0W8e9IXXIFiDycbIwKH8Eg9GmUAAGpQGocn7zOgqJbMghsNQ09MJN3CxHw2b7FeoiSFI1gKAoWgaxAcjKL4o2TayaGrH5-HQBY71+wAJiFgr7pk6OY6QVdFoAITIaZJNjtP06gC6IDUzAlJSKORLQDTrUlxbRQAZUgqJRSwcv0wEW9DOM0ASIAARorC+Ho4Bs1zCzi600uxAICNaCjGVG6MiMW-blJO+73vk+AOxI2UEgLMK6yS61TwoJ6Bgk+mYGoPcybpsauvez4ML66ipExYlnZEllxaR9X9wsjfsflDhdK+CoxWKIVZ6FynFCcoAlzJRimLBGBE4QAEIn4JE-nERIoDFDjgREiQ45BhjrhIOQEgcISJPglOkc4YDPa4yVsAihGDGB0zOpZLeg8UilXKvvegh8WpMjPvVRqYgeE1VFkzCCI1erbSGmoEa40+E+WwJfCKoA1qV3VDYLaA0pEyLGgdUAbNTrnQLsgFgN07ryTUo9XQB5F7TDtseWWH0oRfRIDee8nDuH-Rqu+ROydj4aiRJgS8kA9L8EEBg5SaBwbuEhn7EicNyaIyimILIAB5NGGMA5JIYFkAAcsddmIdOG5PyUQpE9NGadTESzRaxTiYFM5qUMgPNwH80RhHEWMD9w4mxtMaWjcuyIwVoYIBqs8aa21rrRm9M+ISxscbdgKEHEYSyFhBZOE8IERsXY4ixCnYuzdsAD2BU5k+z9pkoOhTw7TKMRnW5UlVwAClkx6EURmVOdyPnCSzldMAecVLmIegPbprRjKvMzKAB55cUk5LBQAdhllPJoAAiJMKY-7gCoBizgSKZlWJxE83QYK-F6i7L-W+-AQoxXQfFCBiVlwpWHHQ8coBAnBL9vweMoAxiME3sVNh7gyorAJWoMFQjXxyJmotMVbVREuxZn1TgO1pF7QmnVeRkLoVwuUSCiMYKNGKq0Sq3R+imE3MQCYzgt16SXQsRLVFIr67bPess5xrjRTCtFZ41874PX12JSlSJ-5onENifEhGyqkYiNxtmfsJFUbox1HEoZRh-z0UcP2Qa0w4kt2oONCpe58gBm0KUfsnTGyB2xjGlu+iSJC3zbjSmksq0kRrULIZ506YhKevm5mkbsZDOba23WXa8X5q5k03mbpsZtOFoyzpEsel9NloM6hIy1bjJ1nTKZBs8WgHtWC+Ziy0LLNWShS2DBrb7sdW9R2ztXYgE9mgK9V9D0aF9jDc5wdtZhwjt8z5dzPhSH7FVEg7R0L+B1Cra12d-0Z2YcVbMoAeFSq9V4S8LQJUCOaqh+gj4RykowwAMklokpDEdBq9tkZgK4Yxbj3GjNmeDJd+UkEFeIFD1VxViyMNDXQigFgRoSklFcgDeNqH46AXtQn6WmqKsxjQAqOE4Eac0lo2ooJ4EsM6FEV4R4Kamo+CNI4H66FhFNfsemzMUASYJpDEbZMsJxCxtjoBlPczMGp3eGpLyWa8oZzjKw1WSsEThwzI1RQpKqRQYz5M4RZVA3ITg-Y3MTvoJ5nUGpNMJZ0y43zBm7NLA461egl5pW4bsyNIcQ4ETAf+kVpkpXQugEi3K6LDm+UKdYxwlJ2INScB86ZvzBXiuYc4WVsLEEItRZi+G8RFX5aVNa-2FrI0GnufASl1T6nvN5YoP54rWZJGIzzaCTRlGdHtfk+wlY-r0t7zFmSq+-YfDUBq7Feh0moEi0gSuQxiGeFPmuyVnA+HXOjadZeF7ooofOCWEhkca0xb9QANLOFuPQag1sHxjWAyjiaZ1QCHXoGYU6vKS6IcCpwNI4Q1CA8U2hgAsiiVgaIgvcCDCkcI+3eFs7G01p84XmvTdlspuw1hLxM9RFYUUcJSPIZCwFkr435vRZivL7DivGuK6m61qrf7YPp0A4QZLb0zUG-uWgBwndxidyp65t6A39N7eGzzqa-C+eK5fgrg7dmgejfjRjWWd4ZuCH8BsCkrog2AUvEMyXLOnC8452oLnOM9wC8m6nxsK2FugHfEMp0qh+xx69JnyTvWrHLfL6kR3Vnuc1Qm877PbXGxvYh7tuvr5DN++I5T6ntPOtsYl8zkvyv0+N+m0OPijZurh95OBKuugY+42Lwnt38ik8p6GWPsmuMm-kzz7jAv4CV8773GQKvSXmsX5r0N0fEadeVfJm9+39sb-5bv930Avf2A07p11xnw+0uLu9eKuD+EEeuhiAK5uMcRuBA-YOS2mnAWUXgZu0BgkfEVu1Q4wR+SBHCjiUaqecmg8O8GWeorqu2QebiZWo29WwiXYtB3q6CX4JA-Yt222oMJur+7ewB3q5M5MRBOIJBe8p6OEOA4ODuMOkhIUVWcI9UVobC-YG+b2AOA+5Ul4IOTCQAA)

With the implementation in support of the following.

```typescript
const router = trpc
.router<{}, TypeBoxInference>(TypeBoxValidation) // <-- auxiliary plugin (no hardcoding)
.query('add', {
  input: Type.Object({ 
    x: Type.Number(), 
    y: Type.Number() 
  }),
  output: Type.Number(),
  resolve: ({ input }) => {
    const { x, y } = input
    return x + y
  },
})

const client = trpc.client<typeof router>('http://...')
const result = client.add({ x: 1, y: 2 })
```
So this would solve this issue, and enable AJV and TypeBox to be integrated without external boxing via closure. Will use the `yup.validateSync()` for the time being, but submitting this in case the implementation is useful for anything.

Cheers!

**Comment by sachinraja** [comment]
That looks awesome @sinclairzx81! I didn't know you could do higher kinded types like that, might be useful if we want to revisit #2137.

The only question I have about this is how to handle having different input parsers across the router. I assume we'd have to have some way of overriding the validation function on the procedure level.

Also development is currently happening on the `next` branch as we're preparing a new major.

**Comment by sinclairzx81** [comment]
@sachinraja Well, the way Fastify approaches inference remapping is via a `withProvider<T>()` mapping function. This function essentially just remaps the current provider (which is an ethereal type) into a new form. In the Fastify case, because they default to JSON schema end to end there's no requirement to override Ajv under the hood; but for tRPC, both inference and validation could be set on the mapping function. So something like the following may work ...

[Updated Example with Inference Remapping](https://www.typescriptlang.org/play?#code/PTAEFpK6dv4YpyXQFAlAFQEoAUBhUPAJwHsAXSgTwAcBTDYJ7ACwEsBnUL0AQ1C1yVCnXqgK+IqIY8AtrQA29OfQB2FPhXZk1EsqBIqyAN3Gs+JACYBjMlfpWeagGb0jam+L5qnJAK4a7KqgimQA5uw2LDas9DYA1tzsapzsDhJSAHRsvEKUNLL+nPTcAmly7IqWoKqxPlxy+qAAYnyc2i7U2GLE5Cbp7twA7nFGoCx8-gAeVZbdKW4eXqA2PqAARt6x9OxmThSs5P7hrKADAhyn7qAJKQ4HvUonKZxZTCxYHNz5Ir3+tCsWlKEjiEhItBsWWOFHcAAoAJS1eiHezNPg2Ly0CibShnRbudQrHxOEx8RTpLRkEg5L6MTAE5biPLtEqk9gCcLqdxRfgkcL+VQaAA0oPEZIpQKoJB4ZUElm05P4tCUUS0Oj0LkCNm0ulBWgmmGGZH8iicnABtGpOI2eNAVmoaj4lRsoDhAC97KLqADRRaGCQOgEdUiSasyAoqo43XwAFYmUWxzi6cCcHZyPiimT0W3TJEsAJBELZt4fTAANXJlOlAC4y2BQOHUjjK5KqTKALxutNxDM17BIjsAPjdEv89H7gQSajIwzUg5HU5nc-roAAotNnUoJ6vG02OoYTbDO+DIdCj+4ADwAbwAvqKAJKuQmeehDuGt6vUhFZACO45Iag4SyECfzkfxNF1NRgNA3dGzsZtVgpdQcS7CgIShGxkI0S9szIFxDwg9x3wAchArISIRVc0k8ap2BId1pgADgARlXVAOM4rjuI4tAWB4gTBKElAWAALXsfjhKk6ShL44IrRIHEACp+G4d1QBccgmhIz0rBIviHCwyxxC1TwoNAcSrE-KUNUvLBQHoaZYV8NSsksrAxAAQTUah3x7FQ+H7LAEX7OExwnUAl1nedQGHSK1GnaK0EM6pxhSY8XAxcRLKfJYiXERznKsbgPIYXKXxWa80EbI9aAg-tDi4ABtEiUjqigSIAXQcpz1GK0B3Tc+xSvobzugAfgGrJGVw74WraiCupHfs1HoMwSDQW8+MwGTdr21BPjEAAhMhpkk-aLsuqA5IUa1QGvHoGFFABlSColFLBnvTARbw0rTQBIgABGijPo4Bs1zfTkviVKTO1cyRpO6ZrPVXQ7J6oqSq+3s+D876gpC0dyXHScEuXGK4qilcUuM5wMqyx76CR8qmQxvqSrEFn8vu6rQFq+rQWa1q1Harq2Zc7BsYC0BJte9UbFmoWFo6zrltAVb1s27awCu3WLpYHALw2na9dN6S+IQg8YRuNCMLQc8iJIG97ws+wudfd9LJRqCqL-ACgJIvgrD00UqsbZX+0GsgNljeIKDhB7ecbaZI6yNRBS2EhEVFJPQGoVP07kTPEQmRtbwRYVef5igC4z+EK95oxk0UMxQoe5XQHL2KRzDvdLZxB7pm9TvYucdrc6MCh-BIPRplAABqPPefvTbfeGdhDndrw7OO06t7fOFEdO72NSRTAjAzWh7f-dwA4tDYSND3mI8ZrIAHkY7jhPc5T1+ADk65ZwbnuPOQUxBZAAUXeuy9gF8wgu1MBDAIGAOzo3UoZAW4RQTmPCCncFw8xAf3e6oAh55xHl2ZWE8UTT1ngvJeZdK7lwtroA8WF2AoVHuhM8bCUK4TEPhQix5SLkUomgHhGgshBysNg3+LFvT9gAEx4LEdhCgWR74yP7HI0BoAlFMO1hAM2etPhSH7LlEg7R0L+B1NPekOsjG6z4o5BSOJsygBZiNfel4Wji36p458TJHwji7HCHxAAyYhL8Hx4JatXMWmArhjFuPcaM2YnHTBcXTdwmUVj+Lyq+Ahhh6BB10IoBYIsBZUzUGgkpagylwIoAg+KiUVxbTQM4u66VskMxwOgzBLR4YajwJYZ0KIrwEF0LCJyj4KkUB7rzBCUya6gAmRoQqz9ZlmNmVrdpGTOlrJIDk8QvTm5mAGWZWyqylkzPySsQq7NGb7xme1UUb94EQXmY2OEtARlyE4P2E5GCzmDN0MMixqhjyXiuYVG57g8kVXoJeJ57jZlDiHITDxnMAn5SRdi18rz3lzJ2R0xSWTDkMzftiDUnAoWTJhSi25BVeoS3hYElFLzQBvMaR8wpUTtk1UJf2Ll49GxNyBRFQF-SQVqFpWs6ZDKEVZjmsLUWnUlVCziarYlezSVdPJSsE+uhzk6g1IUuE-k+z8B8oTMKxMIpVPwVUnZbiWZPnptvHAwTQA4F8dwQ2jtLw+GoKKINopGTuJHJNXuTUADSzhbj0GoAIh8nUzGxu6ptUAK01ruHSZktxnlOBpHCGoN13Tt4AFkUSsDRPciWQYUjhFhazOtfisWMueRBAl3K5mj16XYawl4q2oisKKOEfKlispxcip87V0XdwVSQKdr5cUds5YStFBiHGOMwLgQgAKjbnW3ftAyMNaZGSLd6o2srrmLu5q2jmZU8UrC7MurwMz3VMsxnzT+OpR53nmbzOqGwKSunXpvZ9iK-6FX3r6x5kH3wSi-CQfshq1DGp9gegN0L5XQacjOg5Ryhx8UbMB0DoAb6AUvLnYdNanAPtAA2tQTbS57lnV21jjZhUQV5u+XOTpVD9lo16TjfMqUsKFeJ1IN76UEY5dxoljZCb+shThigzb8ofvLeICJhbi2lsI1lId1aRNyY4wpzdQH-Agd5OBN6aMaMmfo8y-qTGWO53Y+p0TCneNwn46MoTTmc4gLIFJ-5nKwsyflWZrzFneaEyvdhul0XINaf1Tp0Aen2AlrLel4zI6NP4vZeZjdxG2km2PSe3dpjQB-1GZwH5Xgj2VZkqeoy4wBOlEa+ILhrpe68xJTiUyJq9TWydmp-9LtYMMbfeIV97aEWIarFKakqHluo3Q9K5T161OFa8MRxsA2dVDelUhdhOEfUMZU1eUNVrg13bRXCPqVp0r9jcxigJuWjmXk9VrIAA)

```typescript
const router = trpc
.router<{}, ZodInference>(ZodValidation) // default inference
.query('add', {
  input: z.object({ 
    x: z.number(), 
    y: z.number() 
  }),
  output: z.number(),
  resolve: ({ input }) => {
    const { x, y } = input
    return x + y
  },
})
.withInference<TypeBoxInference>(TypeBoxValidation) // remapped inference (if required)
.query('sub', {
  input: Type.Object({
    x: Type.Number(),
    y: Type.Number()
  }),
  output: Type.Number(),
  resolve: ({ input }) => {
    const { x, y } = input
    return x + y
  },
})

const client = trpc.client<typeof router>('...')
client.add({ x: 1, y: 2 }) // zod inference
client.sub({ x: 1, y: 2 }) // typebox inference

```

**Comment by sachinraja** [comment]
Going to close this because the original issue is fixed in v10. I just tried implementing type providers but performance got worse and code complexity increased so I don't think we can move forward with that. Thanks for the idea though!

**Comment by sachinraja** [comment]
@sinclairzx81 sorry for the delayed response. As I said, it works on v10, so you should try `10.0.0-proxy-beta.15`.

**Comment by sinclairzx81** [comment]
@sachinraja Tested `@trpc/server@10.0.0-proxy-beta.15` but still see the same issue. 

<details>
   <summary>Repro Code</summary>
   
   ```typescript
   import { TypeCompiler } from '@sinclair/typebox/compiler'
import { Type, TSchema } from '@sinclair/typebox'
import * as trpc from '@trpc/server'

export function Compile<T extends TSchema>(schema: T, references: TSchema[] = []) {
  const check = TypeCompiler.Compile(schema, references)
  return (input: unknown) => {
    if(check.Check(input)) return input
    throw Error('Invalid Input')
  }
}

const router = trpc.router().query('/', {
  input: Compile(Type.Number()),  // ok   - input: ProcedureParser<number>
  resolve:({ input }) => {}       // fail - input: unknown
})
   ```
</details>

![image](https://user-images.githubusercontent.com/3048342/194733021-b17e6186-ec80-4983-a647-c521b27c5201.png)

**Comment by sachinraja** [comment]
That's the interop API, which we've kept for backward compatibility. Here it is working with the new API: https://stackblitz.com/edit/typescript-ywim3q?file=index.ts

**Comment by sinclairzx81** [comment]
@sachinraja Ah right, a new API!!! That looks like it's working great :) 

Good work!
