### ISSUE TITLE
bug: skipBatch in context does not work

### ISSUE THREAD

**Issue by slhck** [trpc/trpc#4139]
### Provide environment information

```
  System:
    OS: macOS 12.6.3
    CPU: (8) arm64 Apple M1 Pro
    Memory: 169.44 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.13.0 - ~/.nvm/versions/node/v18.13.0/bin/node
    Yarn: 1.22.15 - ~/.nvm/versions/node/v18.13.0/bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v18.13.0/bin/npm
    Watchman: 2023.02.20.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 111.0.5563.146
    Edge: 111.0.1661.62
    Firefox: 109.0.1
    Safari: 16.4
  npmPackages:
    @tanstack/react-query: ^4.28.0 => 4.28.0 
    @trpc/client: ^10.18.0 => 10.18.0 
    @trpc/next: ^10.18.0 => 10.18.0 
    @trpc/react-query: ^10.18.0 => 10.18.0 
    @trpc/server: ^10.18.0 => 10.18.0 
    next: 13.2.4 => 13.2.4 
    react: 18.2.0 => 18.2.0 
    typescript: 5.0.3 => 5.0.3 
```

### Describe the bug

I am following the example here: https://trpc.io/docs/v9/links

However, this leads to a type error:

```
    Type '{ skipBatch: true; }' is not assignable to type 'Context<QueryClient | undefined>'.
```

### Link to reproduction

https://stackblitz.com/edit/github-d5j1eb?file=src/pages/index.tsx

### To reproduce

- Set up the minimal Next.js trpc example
- Modify the configuration to use `splitLink` and `skipBatch` in the context
- Add `skipBatch` to the `useQuery` options
- Observe the TypeScript error

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

**Comment by KATT** [comment]
This is confusing because react-query has a prop called `context` as well. 

Fixed your example: https://stackblitz.com/edit/github-d5j1eb?file=src%2Fpages%2Findex.tsx

Could be improved in the docs.

**Comment by slhck** [comment]
Thanks for the feedback. The example link still shows the type error for me though? Perhaps you didn't save the changes?

<img width="986" alt="image" src="https://user-images.githubusercontent.com/582444/230347295-b9bb7928-a393-439b-bd76-cb765f2bd80a.png">

I notice I found this on an old version of the docs, so this is not even part of the v10 docs … perhaps Google led me there. Maybe this is more suitable? https://trpc.io/docs/links/httpBatchLink#disabling-request-batching

**Comment by KATT** [comment]
see https://stackblitz.com/edit/github-d5j1eb-ajyjyn?file=src%2Fpages%2Findex.tsx

**Comment by slhck** [comment]
Ah gotcha, I was missing the `trpc` property. Thanks again.

So it's:

```typescript
  const result = trpc.greeting.useQuery(
    { name: 'client' },
    {
      trpc: {
        context: {
          skipBatch: true,
        },
      },
    }
```

and not:

```typescript
  const result = trpc.greeting.useQuery(
    { name: 'client' },
    {
      context: {
        skipBatch: true,
      },
    }
```
