### ISSUE TITLE
bug: httpBatchStreamLink: React Native (Expo) stream ends with TypeError while same stream works in web (Vite)

### ISSUE THREAD

**Issue by AkisArou** [trpc/trpc#6955]
### Provide environment information

  System:
    OS: Linux 6.16 Arch Linux
    CPU: (8) x64 Intel(R) Core(TM) Ultra 5 226V
    Memory: 6.43 GB / 14.97 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 22.18.0 - ~/.asdf/installs/nodejs/22.18.0/bin/node
    npm: 11.6.0 - ~/.asdf/plugins/nodejs/shims/npm
    pnpm: 10.17.0 - ~/.asdf/installs/nodejs/22.18.0/bin/pnpm
    Watchman: 20250727.093445.0 - /usr/bin/watchman
  Browsers:
    Brave Browser: 140.1.82.170
  npmPackages:
    typescript: catalog: => 5.9.2 
    expo => 54.0.9
    react-native => "0.81.4"
   @trpc/client => 11.5.0
   @trpc/server => 11.5.0
   @trpc/tanstack-react-query => 11.5.0
   @tanstack/react-query => 5.90.1

### Describe the bug

A simple streaming query (async generator) works correctly in a Vite (web) client using `httpBatchStreamLink`, but in an Expo (React Native) app the stream delivers all data and then throws:

```text
TypeError: The stream is not in a state that permits close
```

The web client completes cleanly; only the Expo client produces the error at stream termination.

### Link to reproduction

https://github.com/AkisArou/trpc-repro

## Reproduction Steps

1. Start the server:

```bash
pnpm dev:node
```

2. (Optional) Start web client (works fine):

```bash
pnpm dev:vite
```

3. Start Expo client:

```bash
pnpm dev:expo
```

4. Observe counts increment; after final emission the Expo client logs the TypeError, while the Vite client finishes normally.

## Server Code (minimal)

```ts
// packages/server/src/_app.ts
import { publicProcedure, router } from "./trpc.ts";

export const appRouter = router({
  greeting: publicProcedure.query(async function* () {
    let count = 1;
    while (count <= 5) {
      await new Promise((res) => setTimeout(res, 1000));
      console.log(`Sending count: ${count}`);
      yield count++;
    }
  }),
});
```

```ts
// apps/node-app/src/index.ts
import { createHTTPServer } from "@trpc/server/adapters/standalone";
import { appRouter } from "@packages/trpc-server/_app.ts";
import cors from "cors";

createHTTPServer({
  router: appRouter,
  middleware: cors(),
}).listen(3000, "0.0.0.0");
```

## Shared Client Setup

```ts
// packages/client/src/trpc.ts
import {
  createTRPCClient as _createTRPCClient,
  httpBatchStreamLink,
  loggerLink,
} from "@trpc/client";
import { createTRPCContext } from "@trpc/tanstack-react-query";
import type { AppRouter } from "@packages/trpc-server/_app.ts";

export const { TRPCProvider, useTRPC } = createTRPCContext<AppRouter>();

export function createTRPCClient({ url, fetch }: { url: string; fetch?: any }) {
  return _createTRPCClient<AppRouter>({
    links: [
      loggerLink({ enabled: () => true }),
      httpBatchStreamLink({ url, fetch }),
    ],
  });
}
```

## Vite Client (Works)

```tsx
// apps/vite-app/src/App.tsx
const query = useQuery(trpc.greeting.queryOptions());
const count = query.data?.at(-1) ?? 0;
```

## Expo Client (Throws on completion)

```tsx
// apps/expo-app/app/_layout.tsx
const [trpcClient] = useState(() =>
  createTRPCClient({
    url: process.env.EXPO_PUBLIC_TRPC_URL,
    fetch: (url, opts) =>
      fetch(url, {
        ...opts,
        reactNative: { textStreaming: true },
      }),
  })
);

const query = useQuery(trpc.greeting.queryOptions());
```

Environment sanity checks (all defined):

```text
TextDecoder / TextDecoderStream / ReadableStream / WritableStream present
```

## Raw Stream Frames (from Vite client)

```json
{"0":[[0],[null,0,0]]}
[0,0,[[{"result":0}],["result",0,1]]]
[1,0,[[{"data":0}],["data",0,2]]]
[2,0,[[0],[null,1,3]]]
[3,1,[[1]]]
[3,1,[[2]]]
[3,1,[[3]]]
[3,1,[[4]]]
[3,1,[[5]]]
[3,1,[[6]]]
[3,1,[[7]]]
[3,1,[[8]]]
[3,1,[[9]]]
[3,1,[[10]]]
[3,0,[[]]]
```

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

**Comment by KATT** [comment]
I really appreciate the effort you put into this report and repro. Thank you!

I did however, struggle to create a failing test to verify that I fixed it. I think I fixed it. Can you test the latest canary? Should be available in `11.5.2-canary.11+aac35fbdc` (#6957)

If it works, let me know

**Comment by AkisArou** [comment]
Thanks for the quick response!

I tried it out, but unfortunately I’m still getting the same error with the same behavior.
I also tested it using a plain fetch stream implementation, and that works fine—so I suspect the issue is on the tRPC side.
As far as I know, Expo uses [web-streams-polyfill](https://github.com/MattiasBuelens/web-streams-polyfill/) under the hood at [expo/virtual/streams.js](https://github.com/expo/expo/blob/main/packages/expo/virtual/streams.js), in case that’s helpful.
(I've updated the repo with the plain fetch implementation, if it helps)

**Comment by KATT** [comment]
I'm really struggling to reproduce it. Do you know the version of web-streams-polyfill it's using? I tried reproducing in #6959 by ponyfilling with the polyfill

Feel free to have a stab by checking out that branch and running `pnpm test 6955`

**Comment by KATT** [comment]
Could you try `11.5.2-alpha-6955-again-2025-09-24-08-18-00.13`?  (#6960)

**Comment by KATT** [comment]
(Double-check that you use the same version for all `@trpc/*`-packages too 🙏 )

**Comment by AkisArou** [comment]
Hey!
I tried `11.5.2-alpha-6955-again-2025-09-24-08-18-00.13`, but still no luck.

Expo is using web-streams-polyfill version 4.1.0, while the latest is 4.2.0. I checked the commits, and ~99% of the changes are infra, ESLint, or TypeScript type updates.

#### Call stack when the error is thrown:

close → [web-streams-polyfill/src/lib/readable-stream/default-controller.ts](https://github.com/MattiasBuelens/web-streams-polyfill/blob/46d22ccb22bd9f6a10f488694cd89b3ca0d2bc9b/src/lib/readable-stream/default-controller.ts#L66)
ReadableStream.start → [expo/packages/expo/src/winter/fetch/FetchResponse.ts](https://github.com/expo/expo/blob/bf1c37873415a5a69a4f0ffa65eaee5daf89211d/packages/expo/src/winter/fetch/FetchResponse.ts#L45)


### Findings from debugging:

From what I can tell, `originalController._state` is already closed by the time `streamController.close()` is called.

<img width="1815" height="936" alt="Image" src="https://github.com/user-attachments/assets/5f1f746f-794c-4e6e-85ad-695044bdb210" />

### Relevant code from the stack:

[ReadableStreamDefaultController.close()](https://github.com/MattiasBuelens/web-streams-polyfill/blob/46d22ccb22bd9f6a10f488694cd89b3ca0d2bc9b/src/lib/readable-stream/default-controller.ts#L71) — where the check fails.

[The underlying state check](https://github.com/MattiasBuelens/web-streams-polyfill/blob/46d22ccb22bd9f6a10f488694cd89b3ca0d2bc9b/src/lib/readable-stream/default-controller.ts#L319)

**Comment by KATT** [comment]
`@tmp` / `11.5.2-alpha-tmp-6955-again.17`? 😅 

basically did a `try/catch` now, my absolute favorite solution

**Comment by AkisArou** [comment]
Nope 🥲  Still the same error!
I tried to debug it further.
Here is what happens from what I've seen:

1. [`source.pipeTo().catch()`](https://github.com/trpc/trpc/blob/466a924bf035bc729339019accf8c19d41200846/packages/server/src/unstable-core-do-not-import/stream/jsonl.ts#L635) is called with the error of `[AbortError: Aborted]`.
2. You [`closeOrAbort()`](https://github.com/trpc/trpc/blob/466a924bf035bc729339019accf8c19d41200846/packages/server/src/unstable-core-do-not-import/stream/jsonl.ts#L602) which cancels all controllers with `controller.error()` and I guess all streams are closed.
3. Lastly, expo's [FetchResponse](https://github.com/expo/expo/blob/5fcf69724a6c6ad6218b4e4a97fb73711bcb5c53/packages/expo/src/winter/fetch/FetchResponse.ts#L45) calls `controller.close()` on `"didComplete"` which causes the error  `[TypeError: The stream is not in a state that permits close]` because you already closed all the streams! (I did comment out the `controller.close()` and no error is thrown!)

**Comment by KATT** [comment]
Okay, I'm sorry for this. I finally got Expo working locally with my local package and did some trial and error - `11.5.2-alpha-tmp-6955-again.19` seems to work for me?

**Comment by AkisArou** [comment]
Hey, it indeed works without any errors! Thank you very much! 😸
